### ISSUE TITLE
Unknown Locale: UTF-8

### ISSUE THREAD

**Issue by POTION4** [Swordfish90/cool-retro-term#416]
```Traceback (most recent call last):
  File "/Users/apple/Library/Python/2.7/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "/Users/apple/Library/Python/2.7/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/Users/apple/Library/Python/2.7/lib/python/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

This is what I get when starting CRT...
OS: Mac OS X
Language: Chinese

**Comment by POTION4** [comment]
Looks like it's a problem with Powerline. iTerm does not have this issue, however. Is it because that CRT does not have UTF8 support? Hope it could be fixed soon 😄

**Comment by bmcgough** [comment]
I have LC_CTYPE=UTF-8 in my cool-retro-term and am experiencing the following:

`-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8)`

As well as various Python errors like the one above.

I believe that `UTF-8` is not a valid value for LC_CTYPE. It is not a complete locale.

I am on OS X where the terminal app has LANG=en_US.UTF-8. Perhaps there is a way to inherit this?
